import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useNavigate } from "react-router-dom";
import { useApp } from "@/contexts/AppContext";
import ParticleBackground from "@/components/ParticleBackground";
import ProfileDropdown from "@/components/ProfileDropdown";
import { ArrowLeft } from "lucide-react";
const CareerDetailsPage = () => {
    const { user } = useApp();
    const navigate = useNavigate();
    return (_jsxs("div", { className: "min-h-screen gradient-bg relative", children: [_jsx(ParticleBackground, {}), _jsx(ProfileDropdown, {}), _jsxs("div", { className: "relative z-10 max-w-3xl mx-auto p-4 md:p-8", children: [_jsxs("button", { onClick: () => navigate("/dashboard"), className: "flex items-center gap-2 text-muted-foreground hover:text-foreground mb-6", children: [_jsx(ArrowLeft, { className: "w-4 h-4" }), " Dashboard"] }), _jsxs("div", { className: "glass-card p-8 animate-fade-in", children: [_jsx("h1", { className: "text-3xl font-bold text-foreground mb-2", children: "Career Details" }), _jsxs("p", { className: "text-muted-foreground mb-6", children: ["Based on your goal: ", user.careerGoal] }), _jsxs("div", { className: "space-y-6", children: [_jsxs("div", { className: "glass-card p-6", children: [_jsx("h2", { className: "font-bold text-foreground text-lg", children: "\uD83D\uDCCA What does this role involve?" }), _jsxs("p", { className: "text-muted-foreground mt-2", children: ["This role requires analyzing data, building solutions, and continuous learning. It aligns with your ", user.skillLevel, " level and ", user.education, " background."] })] }), _jsxs("div", { className: "glass-card p-6", children: [_jsx("h2", { className: "font-bold text-foreground text-lg", children: "\uD83D\uDEE0\uFE0F Required Skills" }), _jsx("div", { className: "flex flex-wrap gap-2 mt-2", children: user.knownSkills.map(s => _jsxs("span", { className: "px-3 py-1 bg-success/10 text-success rounded-full text-sm", children: [s, " \u2705"] }, s)) })] }), _jsxs("div", { className: "glass-card p-6", children: [_jsx("h2", { className: "font-bold text-foreground text-lg", children: "\uD83D\uDCC8 Growth Path" }), _jsxs("p", { className: "text-muted-foreground mt-2", children: ["With ", user.learningTime, "/day of practice, you can be job-ready in 2-4 months. Keep completing daily challenges and building projects!"] })] }), _jsxs("div", { className: "glass-card p-6", children: [_jsx("h2", { className: "font-bold text-foreground text-lg", children: "\uD83D\uDCB0 Expected Salary Range" }), _jsx("p", { className: "text-muted-foreground mt-2", children: "Entry level: $40,000 - $65,000/year. Grows significantly with experience and certifications." })] })] })] })] })] }));
};
export default CareerDetailsPage;
