import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
// 15 template style configs
const TEMPLATE_STYLES = {
    "azure-executive": { layout: "sidebar-left", primary: "#1e3a8a", secondary: "#3b82f6", accent: "#60a5fa", bg: "#ffffff", sidebarBg: "#1e3a8a", sidebarText: "#ffffff", font: "'Georgia', serif", headingStyle: "uppercase" },
    "emerald-modern": { layout: "sidebar-left", primary: "#065f46", secondary: "#10b981", accent: "#34d399", bg: "#ffffff", sidebarBg: "#064e3b", sidebarText: "#ecfdf5", font: "'Inter', sans-serif", headingStyle: "uppercase" },
    "crimson-bold": { layout: "sidebar-right", primary: "#991b1b", secondary: "#dc2626", accent: "#f87171", bg: "#ffffff", sidebarBg: "#7f1d1d", sidebarText: "#ffffff", font: "'Inter', sans-serif", headingStyle: "uppercase" },
    "midnight-pro": { layout: "sidebar-left", primary: "#0f172a", secondary: "#334155", accent: "#64748b", bg: "#ffffff", sidebarBg: "#0f172a", sidebarText: "#f1f5f9", font: "'Inter', sans-serif", headingStyle: "uppercase" },
    "sunset-creative": { layout: "header-band", primary: "#9a3412", secondary: "#ea580c", accent: "#fb923c", bg: "#fff7ed", font: "'Poppins', sans-serif", headingStyle: "uppercase" },
    "minimal-mono": { layout: "minimal", primary: "#000000", secondary: "#404040", accent: "#737373", bg: "#ffffff", font: "'Helvetica', sans-serif", headingStyle: "uppercase" },
    "tech-cyan": { layout: "two-column", primary: "#0e7490", secondary: "#06b6d4", accent: "#22d3ee", bg: "#ffffff", font: "'JetBrains Mono', monospace", headingStyle: "uppercase" },
    "rose-elegant": { layout: "centered", primary: "#9f1239", secondary: "#e11d48", accent: "#fb7185", bg: "#fff1f2", font: "'Playfair Display', serif", headingStyle: "capitalize" },
    "violet-creative": { layout: "sidebar-right", primary: "#5b21b6", secondary: "#7c3aed", accent: "#a78bfa", bg: "#ffffff", sidebarBg: "#4c1d95", sidebarText: "#ede9fe", font: "'Poppins', sans-serif", headingStyle: "uppercase" },
    "gold-luxury": { layout: "header-band", primary: "#78350f", secondary: "#b45309", accent: "#d97706", bg: "#fffbeb", font: "'Georgia', serif", headingStyle: "uppercase" },
    "teal-clean": { layout: "two-column", primary: "#115e59", secondary: "#0d9488", accent: "#2dd4bf", bg: "#ffffff", font: "'Inter', sans-serif", headingStyle: "uppercase" },
    "graphite-classic": { layout: "minimal", primary: "#1f2937", secondary: "#4b5563", accent: "#9ca3af", bg: "#ffffff", font: "'Times New Roman', serif", headingStyle: "uppercase" },
    "indigo-timeline": { layout: "timeline", primary: "#3730a3", secondary: "#4f46e5", accent: "#818cf8", bg: "#ffffff", font: "'Inter', sans-serif", headingStyle: "uppercase" },
    "olive-natural": { layout: "sidebar-left", primary: "#3f6212", secondary: "#65a30d", accent: "#a3e635", bg: "#ffffff", sidebarBg: "#365314", sidebarText: "#ecfccb", font: "'Inter', sans-serif", headingStyle: "uppercase" },
    "slate-corporate": { layout: "header-band", primary: "#1e293b", secondary: "#475569", accent: "#94a3b8", bg: "#ffffff", font: "'Inter', sans-serif", headingStyle: "uppercase" },
};
const ResumePreview = ({ templateId, resumeData, user, hiddenFields, fontSize = 14 }) => {
    const style = TEMPLATE_STYLES[templateId] || TEMPLATE_STYLES["minimal-mono"];
    const h = (k) => hiddenFields?.has(k) ?? false;
    const data = {
        name: resumeData.name || user.username || "Your Name",
        title: h("title") ? "" : (resumeData.title || user.careerGoal || "Professional"),
        email: h("email") ? "" : (resumeData.email || user.email || ""),
        phone: h("phone") ? "" : (resumeData.phone || user.phone || ""),
        location: h("location") ? "" : (resumeData.location || ""),
        linkedin: h("linkedin") ? "" : (resumeData.linkedin || ""),
        website: h("website") ? "" : (resumeData.website || ""),
        summary: h("summary") ? "" : (resumeData.summary || ""),
        education: h("education") ? "" : (resumeData.education || user.education || ""),
        experience: h("experience") ? "" : (resumeData.experience || ""),
        projects: h("projects") ? "" : (resumeData.projects || ""),
        skills: h("skills") ? [] : (resumeData.skills || user.knownSkills.join(", ")).split(",").map(s => s.trim()).filter(Boolean),
        certifications: h("certifications") ? "" : (resumeData.certifications || ""),
        languages: h("languages") ? "" : (resumeData.languages || ""),
        hobbies: h("hobbies") ? "" : (resumeData.hobbies || ""),
        photo: resumeData.photo || "",
    };
    const headingTransform = style.headingStyle === "uppercase" ? "uppercase" : style.headingStyle === "capitalize" ? "capitalize" : "none";
    // Reusable section heading
    const SectionTitle = ({ children, light = false }) => (_jsx("h2", { style: {
            color: light ? style.sidebarText : style.primary,
            textTransform: headingTransform,
            borderBottom: `2px solid ${light ? style.accent : style.secondary}`,
            fontSize: "13px",
            fontWeight: 700,
            letterSpacing: "1.5px",
            paddingBottom: "4px",
            marginBottom: "10px",
            marginTop: "16px",
        }, children: children }));
    const Para = ({ text, light = false }) => text ? (_jsx("p", { style: { color: light ? style.sidebarText : "#374151", fontSize: "12px", lineHeight: 1.6, whiteSpace: "pre-wrap", marginBottom: "8px", opacity: light ? 0.92 : 1 }, children: text })) : null;
    const ContactLine = ({ icon, value, light = false }) => value ? (_jsxs("div", { style: { display: "flex", alignItems: "center", gap: "6px", fontSize: "11px", color: light ? style.sidebarText : "#4b5563", marginBottom: "4px", opacity: light ? 0.95 : 1 }, children: [_jsx("span", { style: { color: light ? style.accent : style.secondary }, children: icon }), _jsx("span", { style: { wordBreak: "break-word" }, children: value })] })) : null;
    const SkillChips = ({ light = false }) => (_jsx("div", { style: { display: "flex", flexWrap: "wrap", gap: "6px" }, children: data.skills.map((s, i) => (_jsx("span", { style: {
                fontSize: "10.5px",
                padding: "3px 9px",
                borderRadius: "12px",
                backgroundColor: light ? `${style.accent}33` : `${style.secondary}1a`,
                color: light ? style.sidebarText : style.primary,
                border: `1px solid ${light ? style.accent + "66" : style.secondary + "55"}`,
                fontWeight: 500,
            }, children: s }, i))) }));
    const Photo = ({ size = 90, light = false }) => data.photo ? (_jsx("img", { src: data.photo, alt: "", style: { width: size, height: size, borderRadius: "50%", objectFit: "cover", border: `3px solid ${light ? style.accent : style.secondary}`, display: "block" } })) : null;
    // ---------- LAYOUTS ----------
    // SIDEBAR LEFT / RIGHT
    if (style.layout === "sidebar-left" || style.layout === "sidebar-right") {
        const sidebar = (_jsxs("div", { style: { width: "35%", padding: "30px 22px", backgroundColor: style.sidebarBg, color: style.sidebarText, display: "flex", flexDirection: "column" }, children: [data.photo && _jsx("div", { style: { display: "flex", justifyContent: "center", marginBottom: "16px" }, children: _jsx(Photo, { size: 100, light: true }) }), _jsx("h1", { style: { fontSize: "22px", fontWeight: 800, textAlign: "center", marginBottom: "4px", letterSpacing: "0.5px", textTransform: headingTransform }, children: data.name }), _jsx("p", { style: { fontSize: "12px", textAlign: "center", opacity: 0.85, marginBottom: "20px" }, children: data.title }), _jsx(SectionTitle, { light: true, children: "Contact" }), _jsx(ContactLine, { icon: "\u2709", value: data.email, light: true }), _jsx(ContactLine, { icon: "\uD83D\uDCDE", value: data.phone, light: true }), _jsx(ContactLine, { icon: "\uD83D\uDCCD", value: data.location, light: true }), _jsx(ContactLine, { icon: "\uD83D\uDD17", value: data.linkedin, light: true }), _jsx(ContactLine, { icon: "\uD83C\uDF10", value: data.website, light: true }), data.skills.length > 0 && (_jsxs(_Fragment, { children: [_jsx(SectionTitle, { light: true, children: "Skills" }), _jsx(SkillChips, { light: true })] })), data.languages && (_jsxs(_Fragment, { children: [_jsx(SectionTitle, { light: true, children: "Languages" }), _jsx(Para, { text: data.languages, light: true })] })), data.hobbies && (_jsxs(_Fragment, { children: [_jsx(SectionTitle, { light: true, children: "Interests" }), _jsx(Para, { text: data.hobbies, light: true })] }))] }));
        const main = (_jsxs("div", { style: { flex: 1, padding: "30px 28px", backgroundColor: style.bg }, children: [data.summary && (_jsxs(_Fragment, { children: [_jsx(SectionTitle, { children: "Profile" }), _jsx(Para, { text: data.summary })] })), data.experience && (_jsxs(_Fragment, { children: [_jsx(SectionTitle, { children: "Experience" }), _jsx(Para, { text: data.experience })] })), data.education && (_jsxs(_Fragment, { children: [_jsx(SectionTitle, { children: "Education" }), _jsx(Para, { text: data.education })] })), data.projects && (_jsxs(_Fragment, { children: [_jsx(SectionTitle, { children: "Projects" }), _jsx(Para, { text: data.projects })] })), data.certifications && (_jsxs(_Fragment, { children: [_jsx(SectionTitle, { children: "Certifications" }), _jsx(Para, { text: data.certifications })] }))] }));
        return (_jsx("div", { style: { display: "flex", minHeight: "1100px", fontFamily: style.font, color: "#111827", backgroundColor: style.bg }, children: style.layout === "sidebar-left" ? _jsxs(_Fragment, { children: [sidebar, main] }) : _jsxs(_Fragment, { children: [main, sidebar] }) }));
    }
    // HEADER BAND
    if (style.layout === "header-band") {
        return (_jsxs("div", { style: { minHeight: "1100px", fontFamily: style.font, backgroundColor: style.bg, color: "#111827" }, children: [_jsxs("div", { style: { backgroundColor: style.primary, color: "#fff", padding: "30px 36px", display: "flex", gap: "20px", alignItems: "center" }, children: [data.photo && _jsx(Photo, { size: 90 }), _jsxs("div", { style: { flex: 1 }, children: [_jsx("h1", { style: { fontSize: "28px", fontWeight: 800, marginBottom: "4px", textTransform: headingTransform, letterSpacing: "1px" }, children: data.name }), _jsx("p", { style: { fontSize: "14px", opacity: 0.9, marginBottom: "10px" }, children: data.title }), _jsxs("div", { style: { display: "flex", flexWrap: "wrap", gap: "14px", fontSize: "11px", opacity: 0.95 }, children: [data.email && _jsxs("span", { children: ["\u2709 ", data.email] }), data.phone && _jsxs("span", { children: ["\uD83D\uDCDE ", data.phone] }), data.location && _jsxs("span", { children: ["\uD83D\uDCCD ", data.location] }), data.linkedin && _jsxs("span", { children: ["\uD83D\uDD17 ", data.linkedin] })] })] })] }), _jsxs("div", { style: { padding: "26px 36px" }, children: [data.summary && (_jsxs(_Fragment, { children: [_jsx(SectionTitle, { children: "Summary" }), _jsx(Para, { text: data.summary })] })), data.experience && (_jsxs(_Fragment, { children: [_jsx(SectionTitle, { children: "Experience" }), _jsx(Para, { text: data.experience })] })), data.education && (_jsxs(_Fragment, { children: [_jsx(SectionTitle, { children: "Education" }), _jsx(Para, { text: data.education })] })), data.skills.length > 0 && (_jsxs(_Fragment, { children: [_jsx(SectionTitle, { children: "Skills" }), _jsx(SkillChips, {})] })), data.projects && (_jsxs(_Fragment, { children: [_jsx(SectionTitle, { children: "Projects" }), _jsx(Para, { text: data.projects })] })), data.certifications && (_jsxs(_Fragment, { children: [_jsx(SectionTitle, { children: "Certifications" }), _jsx(Para, { text: data.certifications })] })), data.languages && (_jsxs(_Fragment, { children: [_jsx(SectionTitle, { children: "Languages" }), _jsx(Para, { text: data.languages })] }))] })] }));
    }
    // MINIMAL
    if (style.layout === "minimal") {
        return (_jsxs("div", { style: { minHeight: "1100px", fontFamily: style.font, backgroundColor: style.bg, color: "#111827", padding: "40px 44px" }, children: [_jsxs("div", { style: { display: "flex", justifyContent: "space-between", alignItems: "flex-start", borderBottom: `3px solid ${style.primary}`, paddingBottom: "16px", marginBottom: "20px" }, children: [_jsxs("div", { children: [_jsx("h1", { style: { fontSize: "32px", fontWeight: 800, color: style.primary, textTransform: headingTransform, letterSpacing: "2px", marginBottom: "4px" }, children: data.name }), _jsx("p", { style: { fontSize: "14px", color: style.secondary, letterSpacing: "1px" }, children: data.title })] }), data.photo && _jsx(Photo, { size: 80 })] }), _jsxs("div", { style: { display: "flex", flexWrap: "wrap", gap: "14px", fontSize: "11px", color: "#4b5563", marginBottom: "20px" }, children: [data.email && _jsxs("span", { children: ["\u2709 ", data.email] }), data.phone && _jsxs("span", { children: ["\uD83D\uDCDE ", data.phone] }), data.location && _jsxs("span", { children: ["\uD83D\uDCCD ", data.location] }), data.linkedin && _jsxs("span", { children: ["\uD83D\uDD17 ", data.linkedin] }), data.website && _jsxs("span", { children: ["\uD83C\uDF10 ", data.website] })] }), data.summary && (_jsxs(_Fragment, { children: [_jsx(SectionTitle, { children: "Profile" }), _jsx(Para, { text: data.summary })] })), data.experience && (_jsxs(_Fragment, { children: [_jsx(SectionTitle, { children: "Experience" }), _jsx(Para, { text: data.experience })] })), data.education && (_jsxs(_Fragment, { children: [_jsx(SectionTitle, { children: "Education" }), _jsx(Para, { text: data.education })] })), data.skills.length > 0 && (_jsxs(_Fragment, { children: [_jsx(SectionTitle, { children: "Skills" }), _jsx(SkillChips, {})] })), data.projects && (_jsxs(_Fragment, { children: [_jsx(SectionTitle, { children: "Projects" }), _jsx(Para, { text: data.projects })] })), data.certifications && (_jsxs(_Fragment, { children: [_jsx(SectionTitle, { children: "Certifications" }), _jsx(Para, { text: data.certifications })] }))] }));
    }
    // TWO COLUMN (balanced)
    if (style.layout === "two-column") {
        return (_jsxs("div", { style: { minHeight: "1100px", fontFamily: style.font, backgroundColor: style.bg, color: "#111827", padding: "32px 36px" }, children: [_jsxs("div", { style: { display: "flex", gap: "20px", alignItems: "center", marginBottom: "20px", paddingBottom: "16px", borderBottom: `3px solid ${style.primary}` }, children: [data.photo && _jsx(Photo, { size: 80 }), _jsxs("div", { style: { flex: 1 }, children: [_jsx("h1", { style: { fontSize: "26px", fontWeight: 800, color: style.primary, textTransform: headingTransform, letterSpacing: "1px" }, children: data.name }), _jsx("p", { style: { fontSize: "13px", color: style.secondary, marginTop: "2px" }, children: data.title }), _jsxs("div", { style: { display: "flex", flexWrap: "wrap", gap: "12px", fontSize: "11px", color: "#4b5563", marginTop: "6px" }, children: [data.email && _jsxs("span", { children: ["\u2709 ", data.email] }), data.phone && _jsxs("span", { children: ["\uD83D\uDCDE ", data.phone] }), data.location && _jsxs("span", { children: ["\uD83D\uDCCD ", data.location] })] })] })] }), _jsxs("div", { style: { display: "grid", gridTemplateColumns: "1.6fr 1fr", gap: "24px" }, children: [_jsxs("div", { children: [data.summary && (_jsxs(_Fragment, { children: [_jsx(SectionTitle, { children: "Summary" }), _jsx(Para, { text: data.summary })] })), data.experience && (_jsxs(_Fragment, { children: [_jsx(SectionTitle, { children: "Experience" }), _jsx(Para, { text: data.experience })] })), data.projects && (_jsxs(_Fragment, { children: [_jsx(SectionTitle, { children: "Projects" }), _jsx(Para, { text: data.projects })] }))] }), _jsxs("div", { children: [data.education && (_jsxs(_Fragment, { children: [_jsx(SectionTitle, { children: "Education" }), _jsx(Para, { text: data.education })] })), data.skills.length > 0 && (_jsxs(_Fragment, { children: [_jsx(SectionTitle, { children: "Skills" }), _jsx(SkillChips, {})] })), data.certifications && (_jsxs(_Fragment, { children: [_jsx(SectionTitle, { children: "Certifications" }), _jsx(Para, { text: data.certifications })] })), data.languages && (_jsxs(_Fragment, { children: [_jsx(SectionTitle, { children: "Languages" }), _jsx(Para, { text: data.languages })] })), data.linkedin && (_jsxs(_Fragment, { children: [_jsx(SectionTitle, { children: "Links" }), _jsx(ContactLine, { icon: "\uD83D\uDD17", value: data.linkedin }), data.website && _jsx(ContactLine, { icon: "\uD83C\uDF10", value: data.website })] }))] })] })] }));
    }
    // CENTERED (elegant)
    if (style.layout === "centered") {
        return (_jsxs("div", { style: { minHeight: "1100px", fontFamily: style.font, backgroundColor: style.bg, color: "#111827", padding: "44px 48px", textAlign: "center" }, children: [data.photo && _jsx("div", { style: { display: "flex", justifyContent: "center", marginBottom: "14px" }, children: _jsx(Photo, { size: 100 }) }), _jsx("h1", { style: { fontSize: "34px", fontWeight: 700, color: style.primary, letterSpacing: "3px", marginBottom: "6px", textTransform: headingTransform }, children: data.name }), _jsx("div", { style: { width: "60px", height: "2px", backgroundColor: style.secondary, margin: "8px auto" } }), _jsx("p", { style: { fontSize: "14px", color: style.secondary, fontStyle: "italic", marginBottom: "12px" }, children: data.title }), _jsxs("div", { style: { display: "flex", justifyContent: "center", flexWrap: "wrap", gap: "14px", fontSize: "11px", color: "#4b5563", marginBottom: "24px" }, children: [data.email && _jsxs("span", { children: ["\u2709 ", data.email] }), data.phone && _jsxs("span", { children: ["\uD83D\uDCDE ", data.phone] }), data.location && _jsxs("span", { children: ["\uD83D\uDCCD ", data.location] })] }), _jsxs("div", { style: { textAlign: "left" }, children: [data.summary && (_jsxs(_Fragment, { children: [_jsx(SectionTitle, { children: "Profile" }), _jsx(Para, { text: data.summary })] })), data.experience && (_jsxs(_Fragment, { children: [_jsx(SectionTitle, { children: "Experience" }), _jsx(Para, { text: data.experience })] })), data.education && (_jsxs(_Fragment, { children: [_jsx(SectionTitle, { children: "Education" }), _jsx(Para, { text: data.education })] })), data.skills.length > 0 && (_jsxs(_Fragment, { children: [_jsx(SectionTitle, { children: "Skills" }), _jsx(SkillChips, {})] })), data.projects && (_jsxs(_Fragment, { children: [_jsx(SectionTitle, { children: "Projects" }), _jsx(Para, { text: data.projects })] }))] })] }));
    }
    // TIMELINE
    return (_jsxs("div", { style: { minHeight: "1100px", fontFamily: style.font, backgroundColor: style.bg, color: "#111827", padding: "32px 36px" }, children: [_jsxs("div", { style: { display: "flex", gap: "20px", alignItems: "center", marginBottom: "24px" }, children: [data.photo && _jsx(Photo, { size: 90 }), _jsxs("div", { style: { flex: 1, borderLeft: `4px solid ${style.primary}`, paddingLeft: "16px" }, children: [_jsx("h1", { style: { fontSize: "28px", fontWeight: 800, color: style.primary, textTransform: headingTransform }, children: data.name }), _jsx("p", { style: { fontSize: "13px", color: style.secondary, marginTop: "2px" }, children: data.title }), _jsxs("div", { style: { display: "flex", flexWrap: "wrap", gap: "12px", fontSize: "11px", color: "#4b5563", marginTop: "6px" }, children: [data.email && _jsxs("span", { children: ["\u2709 ", data.email] }), data.phone && _jsxs("span", { children: ["\uD83D\uDCDE ", data.phone] }), data.location && _jsxs("span", { children: ["\uD83D\uDCCD ", data.location] }), data.linkedin && _jsxs("span", { children: ["\uD83D\uDD17 ", data.linkedin] })] })] })] }), _jsxs("div", { style: { borderLeft: `2px solid ${style.accent}`, paddingLeft: "20px", marginLeft: "8px" }, children: [data.summary && (_jsxs(_Fragment, { children: [_jsx(SectionTitle, { children: "About" }), _jsx(Para, { text: data.summary })] })), data.experience && (_jsxs(_Fragment, { children: [_jsx(SectionTitle, { children: "Experience" }), _jsx(Para, { text: data.experience })] })), data.education && (_jsxs(_Fragment, { children: [_jsx(SectionTitle, { children: "Education" }), _jsx(Para, { text: data.education })] })), data.skills.length > 0 && (_jsxs(_Fragment, { children: [_jsx(SectionTitle, { children: "Skills" }), _jsx(SkillChips, {})] })), data.projects && (_jsxs(_Fragment, { children: [_jsx(SectionTitle, { children: "Projects" }), _jsx(Para, { text: data.projects })] })), data.certifications && (_jsxs(_Fragment, { children: [_jsx(SectionTitle, { children: "Certifications" }), _jsx(Para, { text: data.certifications })] }))] })] }));
};
export default ResumePreview;
